"project_identifier" : "wildbeast"
"api_key_env": CROWDIN_API_KEY
"preserve_hierarchy": true

files: [
 {
  "source" : "/docs/*.md",
  "translation" : "/docs/%locale_with_underscore%/%original_file_name%",
 }
]