version: 2
jobs:
  noop:
    docker:
      - image: python:3.5
    steps:
      - run:
          name: Do nothing
          command: exit 0
  build:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
  deploy:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: |
            . venv/bin/activate
            mkdocs build
      - add_ssh_keys:
          fingerprints:
              - "98:3f:0a:7d:6c:b9:3f:c1:88:9f:71:10:5a:d3:c0:e6"
      - run:
          name: Deploy
          command: |
            . venv/bin/activate
            git config user.email 9768134+Dougley@users.noreply.github.com
            mkdocs gh-deploy
workflows:
  version: 2
  gh-pages:
    jobs:
      - noop:
          filters:
            branches:
              only: gh-pages
      - build
      - deploy:
          filters:
            branches:
              only: master