version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Compile
          command: mkdocs build
      - run:
          name: Deploy
          command: |
            git config user.email 9768134+Dougley@users.noreply.github.com
            mkdocs gh-deploy
workflows:
  version: 2
  crowdin:
    jobs:
      - build:
          filters:
            branches:
              only: /master/